### ISSUE TITLE
Loss 0 on image triangulation and perlin noise

### ISSUE THREAD

**Issue by qikangchen** [ChezJrk/teg_applications#2]
For a uni seminar, I tried to run the image triangulation. But unfortunately, the following output occurred while running the program:
 
![image](https://user-images.githubusercontent.com/59102264/147162531-9425c3fa-6015-4461-b5d4-68624140ec96.png)

The resulting image is complete black. 

My tutor also tried the program on his machine at home and on the machine at our university. The same black image was generated with loss 0 at every iteration. 

The perlin noise also only yielded loss 0 and black images. The spring example works fine.

Here are the ouputs of `cmake ..` and `make` from the image triangulation built:

> -- The CXX compiler identification is GNU 9.3.0
-- The CUDA compiler identification is NVIDIA 11.4.48
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda-11.4/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda-11.4/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-11.4 (found version "11.4")
-- Found OpenCV: /home/kang/anaconda3 (found version "4.5.5")
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kang/cga/teg_applications/graphics/triangulation/build

> Scanning dependencies of target teg
[ 50%] Built target teg
Scanning dependencies of target test
[ 54%] Building CUDA object CMakeFiles/test.dir/test.cu.o
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh: In member function ‘AABB SplineTriangle::aabb(Vertex*)’:
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh:169:1: warning: no return statement in function returning non-void [-Wreturn-type]
  169 |     }
      | ^
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh: In function ‘int compute_triangle_regularization(TriMesh*, DTriMesh*, float)’:
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh:69:1: warning: no return statement in function returning non-void [-Wreturn-type]
   69 | }
      | ^
[ 58%] Linking CUDA device code CMakeFiles/test.dir/cmake_device_link.o
[ 62%] Linking CUDA executable test
[ 62%] Built target test
Scanning dependencies of target triangulate_quadratic
[ 66%] Building CUDA object CMakeFiles/triangulate_quadratic.dir/triangulate_quadratic.cu.o
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_quadratic.cu(58): warning: variable "pcolor_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_quadratic.cu(61): warning: variable "tcolor_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_quadratic.cu(64): warning: variable "vertices_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_quadratic.cu(67): warning: variable "indices_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh: In member function ‘AABB SplineTriangle::aabb(Vertex*)’:
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh:169:1: warning: no return statement in function returning non-void [-Wreturn-type]
  169 |     }
      | ^
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh: In function ‘int compute_triangle_regularization(TriMesh*, DTriMesh*, float)’:
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh:69:1: warning: no return statement in function returning non-void [-Wreturn-type]
   69 | }
      | ^
[ 70%] Linking CUDA device code CMakeFiles/triangulate_quadratic.dir/cmake_device_link.o
[ 75%] Linking CUDA executable triangulate_quadratic
[ 75%] Built target triangulate_quadratic
Scanning dependencies of target triangulate_linear
[ 79%] Building CUDA object CMakeFiles/triangulate_linear.dir/triangulate_linear.cu.o
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/linear.cuh(141): warning: variable "num_pixels" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_linear.cu(61): warning: variable "pcolor_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_linear.cu(64): warning: variable "tcolor_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_linear.cu(67): warning: variable "vertices_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_linear.cu(70): warning: variable "indices_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh: In member function ‘AABB SplineTriangle::aabb(Vertex*)’:
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh:169:1: warning: no return statement in function returning non-void [-Wreturn-type]
  169 |     }
      | ^
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh: In function ‘int compute_triangle_regularization(TriMesh*, DTriMesh*, float)’:
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh:69:1: warning: no return statement in function returning non-void [-Wreturn-type]
   69 | }
      | ^
[ 83%] Linking CUDA device code CMakeFiles/triangulate_linear.dir/cmake_device_link.o
[ 87%] Linking CUDA executable triangulate_linear
[ 87%] Built target triangulate_linear
Scanning dependencies of target triangulate_const
[ 91%] Building CUDA object CMakeFiles/triangulate_const.dir/triangulate_const.cu.o
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_const.cu(261): warning: variable "pcolor_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_const.cu(264): warning: variable "tcolor_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_const.cu(267): warning: variable "vertices_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangulate_const.cu(270): warning: variable "indices_sz" was declared but never referenced
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh(169): warning: missing return statement at end of non-void function "SplineTriangle::aabb"
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh(69): warning: missing return statement at end of non-void function "compute_triangle_regularization"
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh: In member function ‘AABB SplineTriangle::aabb(Vertex*)’:
/home/kang/cga/teg_applications/graphics/triangulation/triangle.cuh:169:1: warning: no return statement in function returning non-void [-Wreturn-type]
  169 |     }
      | ^
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh: In function ‘int compute_triangle_regularization(TriMesh*, DTriMesh*, float)’:
/home/kang/cga/teg_applications/graphics/triangulation/common.cuh:69:1: warning: no return statement in function returning non-void [-Wreturn-type]
   69 | }
      | ^
[ 95%] Linking CUDA device code CMakeFiles/triangulate_const.dir/cmake_device_link.o
[100%] Linking CUDA executable triangulate_const
[100%] Built target triangulate_const

**Comment by saipraveenb25** [comment]
@qikangchen: Thank you for bringing this to my attention. 
I had some trouble reproducing this bug, but I believe I have tracked it down to the hard-coded GPU architecture flags in [CMakeLists.txt:L15](https://github.com/ChezJrk/teg_applications/blob/30777bbff61fe4f9bbf7771e9ef3ea097144ccfb/graphics/triangulation/CMakeLists.txt#L15). It appears that I've set it to Compute Capability 7.5 for the RTX 20-series GPUs, and that (silently) fails if you have a different GPU model.

We're working on adding some auto-detect code to avoid this issue. In the meantime, you can fix this for your platform by setting `--gpu_architecture` and `--gpu_code` flags in CMakeLists.txt to the appropriate values. You can refer to this [list](https://en.wikipedia.org/wiki/CUDA#GPUs_supported) find the right _compute capability_ number for your GPU model.

**Comment by qikangchen** [comment]
Perfect, thanks! This works great. I changed it to work for our GTX 3090 with `set(CMAKE_CUDA_FLAGS "--gpu-architecture=compute_86 --gpu-code=sm_86")`
